// Builds src/ui/icon_data.rs: the Lucide icons (ISC licence) the interface uses, as SVG.
// Run with the old app's node_modules: node scripts/icons.mjs legacy/node_modules
import { readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'
import { pathToFileURL } from 'node:url'

const modules = process.argv[2] ?? 'node_modules'
const dir = join(modules, 'lucide-react/dist/esm/icons')
// Every icon of the first Tratto, plus a few the new interface needs.
const names = new Set(['arrow-left', 'x', 'chevron-right', 'chevron-down', 'check', 'grip-vertical', 'circle-help', 'message-circle', 'sticky-note', 'image', 'external-link', 'wifi-off', 'users', 'log-out', 'monitor', 'sun', 'moon'])
const src = join(modules, '..', 'src')
const walk = (d) => readdirSync(d, { withFileTypes: true }).flatMap((e) => (e.isDirectory() ? walk(join(d, e.name)) : [join(d, e.name)]))
for (const file of walk(src).filter((f) => /\.tsx?$/.test(f))) {
  const text = readFileSync(file, 'utf8')
  for (const m of text.matchAll(/import\s*\{([^}]+)\}\s*from\s*'lucide-react'/g)) {
    for (const part of m[1].split(',')) {
      const name = part.trim().split(/\s+as\s+/)[0]
      if (name) names.add(name.replace(/([a-z0-9])([A-Z])/g, '$1-$2').replace(/([a-z])([0-9])/g, '$1-$2').replace(/([A-Z])([A-Z][a-z])/g, '$1-$2').toLowerCase())
    }
  }
}
const out = []
for (const name of [...names].sort()) {
  let node
  try {
    // Old names re-export the renamed icon: follow them.
    let file = `${name}.mjs`
    const alias = readFileSync(join(dir, file), 'utf8').match(/export \{ default \} from '\.\/(.+?)'/)
    if (alias) file = alias[1]
    node = (await import(pathToFileURL(resolve(dir, file)).href)).__iconData.node
  } catch {
    console.warn('missing', name)
    continue
  }
  const body = node.map(([tag, attrs]) => `<${tag} ${Object.entries(attrs).filter(([k]) => k !== 'key').map(([k, v]) => `${k}="${v}"`).join(' ')}/>`).join('')
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#fff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">${body}</svg>`
  out.push(`    ("${name}", r##"${svg}"##),`)
}
writeFileSync('src/ui/icon_data.rs', `//! Lucide icons (ISC licence, lucide.dev), generated by scripts/icons.mjs.\n\npub static ICONS: &[(&str, &str)] = &[\n${out.join('\n')}\n];\n`)
console.log(out.length, 'icons')
