; Italian texts of the cargo-packager installer, which ships no Italian file of its own.
LangString addOrReinstall ${LANG_ITALIAN} "Aggiungi o reinstalla i componenti"
LangString alreadyInstalled ${LANG_ITALIAN} "Già installato"
LangString alreadyInstalledLong ${LANG_ITALIAN} "${PRODUCTNAME} ${VERSION} è già installato. Scegli cosa fare e premi Avanti per continuare."
LangString appRunning ${LANG_ITALIAN} "${PRODUCTNAME} è aperto. Chiudilo e riprova."
LangString appRunningOkKill ${LANG_ITALIAN} "${PRODUCTNAME} è aperto.$\nPremi OK per chiuderlo."
LangString chooseMaintenanceOption ${LANG_ITALIAN} "Scegli l'operazione di manutenzione da eseguire."
LangString choowHowToInstall ${LANG_ITALIAN} "Scegli come installare ${PRODUCTNAME}."
LangString createDesktop ${LANG_ITALIAN} "Crea un collegamento sul desktop"
LangString dontUninstall ${LANG_ITALIAN} "Non disinstallare"
LangString dontUninstallDowngrade ${LANG_ITALIAN} "Non disinstallare (questo installer non permette di tornare a una versione precedente senza disinstallare)"
LangString failedToKillApp ${LANG_ITALIAN} "Non riesco a chiudere ${PRODUCTNAME}. Chiudilo e riprova."
LangString installingWebview2 ${LANG_ITALIAN} "Installazione di WebView2…"
LangString newerVersionInstalled ${LANG_ITALIAN} "È già installata una versione più recente di ${PRODUCTNAME}. Installarne una più vecchia è sconsigliato; se vuoi farlo, conviene prima disinstallare quella attuale. Scegli cosa fare e premi Avanti per continuare."
LangString older ${LANG_ITALIAN} "più vecchia"
LangString olderOrUnknownVersionInstalled ${LANG_ITALIAN} "Sul PC c'è una versione $R4 di ${PRODUCTNAME}. Conviene disinstallarla prima di installare questa. Scegli cosa fare e premi Avanti per continuare."
LangString silentDowngrades ${LANG_ITALIAN} "Questo installer non permette di tornare a una versione precedente in modalità silenziosa: usa l'installer con la finestra.$\n"
LangString unableToUninstall ${LANG_ITALIAN} "Impossibile disinstallare."
LangString uninstallApp ${LANG_ITALIAN} "Disinstalla ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_ITALIAN} "Disinstalla prima di installare"
LangString unknown ${LANG_ITALIAN} "sconosciuta"
LangString deleteAppData ${LANG_ITALIAN} "Elimina anche le lavagne salvate su questo PC"
